#!/bin/bash
# ═══════════════════════════════════════════════════════════
# OCP Setup Wizard — First-run interactive configuration
# ═══════════════════════════════════════════════════════════
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

ENV_FILE=".env"

echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║       Orange Cheese Pizza — Setup Wizard         ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Check prerequisites ──
echo -e "${BOLD}Checking prerequisites...${NC}"

check_cmd() {
    if command -v "$1" &> /dev/null; then
        echo -e "  ${GREEN}✓${NC} $1 found"
        return 0
    else
        echo -e "  ${RED}✗${NC} $1 not found — ${YELLOW}$2${NC}"
        return 1
    fi
}

MISSING=0
check_cmd docker "install from https://docs.docker.com/get-docker/" || MISSING=1
check_cmd docker compose "included with Docker Desktop" || MISSING=1
check_cmd openssl "install via: apt install openssl / brew install openssl" || MISSING=1

if [ $MISSING -eq 1 ]; then
    echo ""
    echo -e "${RED}Install missing prerequisites and run again.${NC}"
    exit 1
fi

echo ""

# ── Generate secrets ──
echo -e "${BOLD}Generating secure secrets...${NC}"
DB_PASSWORD=$(openssl rand -hex 16)
BOT_ADMIN_KEY=$(openssl rand -hex 16)
WEBHOOK_SECRET=$(openssl rand -hex 16)
EVOLUTION_API_KEY=$(openssl rand -hex 16)
EVOLUTION_INSTANCE_TOKEN=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen 2>/dev/null || openssl rand -hex 16)
echo -e "  ${GREEN}✓${NC} Secrets generated"
echo ""

# ── Restaurant info ──
echo -e "${BOLD}Restaurant Information${NC}"
echo -e "  (Press Enter to skip / use defaults)"
echo ""

read -p "  Restaurant name [Orange Cheese Pizza]: " RESTAURANT_NAME
RESTAURANT_NAME=${RESTAURANT_NAME:-"Orange Cheese Pizza"}

read -p "  Restaurant WhatsApp number (e.g. 919876543210) []: " RESTAURANT_WHATSAPP_NUMBER
RESTAURANT_WHATSAPP_NUMBER=${RESTAURANT_WHATSAPP_NUMBER:-""}

read -p "  Default delivery fee [0]: " DELIVERY_FEE
DELIVERY_FEE=${DELIVERY_FEE:-"0"}

echo ""

# ── Deployment mode ──
echo -e "${BOLD}Deployment Mode${NC}"
echo "  1) Docker (recommended — everything containerized)"
echo "  2) Local development (manual setup)"
echo ""
read -p "  Select mode [1]: " DEPLOY_MODE
DEPLOY_MODE=${DEPLOY_MODE:-"1"}
echo ""

# ── Write .env ──
cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════
# OCP Environment Configuration — Generated by setup wizard
# ═══════════════════════════════════════════════════════════

# ── Database ──
DB_PASSWORD=${DB_PASSWORD}

# ── Bot ──
BOT_ADMIN_KEY=${BOT_ADMIN_KEY}
EVOLUTION_WEBHOOK_SECRET=${WEBHOOK_SECRET}
EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
EVOLUTION_INSTANCE=OCP
EVOLUTION_INSTANCE_TOKEN=${EVOLUTION_INSTANCE_TOKEN}
RESTAURANT_NAME=${RESTAURANT_NAME}
RESTAURANT_WHATSAPP_NUMBER=${RESTAURANT_WHATSAPP_NUMBER}
DELIVERY_FEE=${DELIVERY_FEE}
CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000

# ── Frontend ──
VITE_API_BASE_URL=
EOF

echo -e "  ${GREEN}✓${NC} ${BOLD}.env${NC} created"
echo ""

# ── Show summary ──
echo -e "${BOLD}${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}Setup complete!${NC}"
echo -e "${BOLD}${CYAN}══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Your admin key:${NC} ${YELLOW}${BOT_ADMIN_KEY}${NC}"
echo -e "  ${BOLD}Save this — you need it to log into the admin dashboard.${NC}"
echo ""
echo -e "  ${BOLD}Services:${NC}"
echo -e "    Frontend:       ${CYAN}http://localhost:3000${NC}"
echo -e "    Bot API:        ${CYAN}http://localhost:8090${NC}"
echo -e "    Evolution GO:   ${CYAN}http://localhost:8080${NC}"
echo -e "    Campaign:       ${CYAN}http://localhost:3001${NC}"
echo ""

if [ "$DEPLOY_MODE" = "1" ]; then
    echo -e "${BOLD}Start everything with:${NC}"
    echo -e "  ${CYAN}docker compose up -d${NC}"
    echo ""
    echo -e "${BOLD}View logs:${NC}"
    echo -e "  ${CYAN}docker compose logs -f${NC}"
    echo ""
    echo -e "${BOLD}Stop everything:${NC}"
    echo -e "  ${CYAN}docker compose down${NC}"
else
    echo -e "${BOLD}Start manually:${NC}"
    echo -e "  Terminal 1:  ${CYAN}cd bot && go run .${NC}"
    echo -e "  Terminal 2:  ${CYAN}cd frontend && npm run dev${NC}"
    echo -e "  Terminal 3:  ${CYAN}cd campaign-runner && npm run dev${NC}"
fi
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Start the services"
echo "  2. Open http://localhost:3000 (or :3000 for Docker)"
echo "  3. Go to /admin and log in with your admin key"
echo "  4. Set up Evolution GO: scan QR code, configure webhook"
echo "  5. Import customers and start sending campaigns!"
echo ""
echo -e "${YELLOW}Evolution GO webhook URL: http://YOUR_SERVER:8090/webhook/evolution${NC}"
echo -e "${YELLOW}Set EVOLUTION_WEBHOOK_SECRET in .env to match Evolution's webhook secret${NC}"
echo ""
